version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mood_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mood
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: